#
# PorkSandwitch website configuration
#

# Name shown in the website header
name: PorkSandwitch

# Short description shown below the name
description: Cool stuff I find on the internet

# Your avatar / profile picture
avatar: https://github.com/PorkSandwitch.png?size=256

#
# Footer links
#

footer-links:
  dribbble:
  email:
  facebook:
  flickr:
  github: PorkSandwitch
  instagram:
  linkedin:
  pinterest:
  rss: true
  twitter:
  stackoverflow:
  youtube:
  googleplus:

#
# Comments
#

disqus:

#
# Analytics
#

google_analytics:

#
# Website URL
#

url: https://porksandwitch.github.io
baseurl: ""

#
# Permalinks
#

permalink: /:title/

#
# Jekyll / Markdown
#

kramdown:
  input: GFM
syntax_highlighter: rouge
syntax_highlighter_opts:
  css_class: 'highlight'

#
# Sass - COMPRESSED FOR SPEED
#

sass:
  style: :compressed

#
# Plugins
#

gems:
  - jekyll-sitemap
  - jekyll-feed

#
# Files excluded
#

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
